CREATE TABLE USER
(
    pk       bigint generated by default as identity,
    id       varchar(64),
    name     varchar(64),
    password varchar(64),
    email    varchar(64),
    PRIMARY KEY (pk),
);

CREATE TABLE COUPON
(
    pk       bigint generated by default as identity,
    category bigint,
    discount bigint,
    name     varchar(64),
    PRIMARY KEY (pk),
    FOREIGN KEY (category) REFERENCES CATEGORY
);

CREATE TABLE CATEGORY
(
    pk   bigint generated by default as identity,
    name varchar(64),
    PRIMARY KEY (pk),
);

CREATE TABLE COUPON_STATE
(
    pk       bigint generated by default as identity,
    coupon   bigint,
    user     bigint,
    quantity bigint,
    PRIMARY KEY (pk),
    FOREIGN KEY (coupon) REFERENCES COUPON,
    FOREIGN KEY (user) REFERENCES USER,
);

CREATE TABLE ITEM
(
    pk       bigint generated by default as identity,
    category bigint,
    quantity bigint,
    price    bigint,
    PRIMARY KEY (pk),
    FOREIGN KEY (category) REFERENCES CATEGORY,
);

CREATE TABLE ORDER
(
    pk     bigint generated by default as identity,
    user   bigint,
    item   bigint,
    coupon bigint,
    PRIMARY KEY (pk),
    FOREIGN KEY (user) REFERENCES USER,
    FOREIGN KEY (item) REFERENCES ITEM,
    FOREIGN KEY (coupon) REFERENCES COUPON,
);